const MAPBOX_ACCESS_TOKEN = "pk.eyJ1IjoicGxndWVkZXMiLCJhIjoiY21sd3IyZnZ2MGR4NDNocHZqeW56M3g5biJ9.XB_NOuoDq2MpDFFXcQjN6Q";

const GOOGLE_SHEETS_API_KEY = "AIzaSyAtUr64NRhhpCKGwbB8q45_-ls2Vk9x7Ts";
const GOOGLE_STREETVIEW_API_KEY = "AIzaSyAtUr64NRhhpCKGwbB8q45_-ls2Vk9x7Ts";

const SHEET_ID = "1pNHyLO6PCJKm9arr_unwoYufGhpuWyKC80uKoJPsv0E";
const SHEET_TAB = "Lista";